spring.application.name=notification-service

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/plazoleta

# JWT RSA-4096 (solo clave pública para verificación)
jwt.public-key=MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA40Tv93e2cpbHpypicqkVqgNMT0gssDgR16RcJnUTibpAVxN/1KQkduCh8ErVDFk9nP5HFoJLWgIBhzOMbuNZop+vLshFASR1NTEFnakh7N3+92n/3RP8rgZ4pPR5WYaoHa9jSBQvKcewt8DglJsusOHqNL8UJdGcl4REEmc+kYQZi7GXlzrJjY0ocItBu0JnQfcyQOFVcOBsn+goawWGKWqa/cnQsCTo2NDxcJf5ivNYgf1pLHScyiKePs6DrwlimVQURA2kvFrCQxxis/6AWBhJ+phQlT6R8wZia7ijia/g/IsQy0NcxDLQD1nf096i9wMjVysFA5zEA/92jC0ylsBdr5px9QVndu1aRW3kB22Hjz+5jYTAxLI+iXoX8KMctEPiGa6rfBZT52BdDJhZE0DnNSt521hAu/xljANdmrQUG6f7C/JTk2g1xhcF+mNjJC9NKuaKfn/225WJY6oKlMcaDWz+VUvtqC0dou02s04sc4X6lrZ7Hdz2wWtzQvLyYPQ4njM6b2iRAOstb433da6qbIBghNXO70ksqr2SuZAwRus+tIeYuunz6w+1b92BunYAZkmmNTDgwdk9fLG2JidSm5n1MP86SF18oXYy7MqZcMFDt+s33OTCvUnPwFcxQ2XBipiyQLVY3eNRdafpLEnklnNyX1IOft7AHEyL3E8CAwEAAQ==

# OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Server
server.port=8084

# Twilio (configurar en variables de entorno)
twilio.account-sid=${TWILIO_ACCOUNT_SID:}
twilio.auth-token=${TWILIO_AUTH_TOKEN:}
twilio.phone-number=${TWILIO_PHONE_NUMBER:}
